language: generic

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- sudo apt-get install -y msttcorefonts
- echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
- sudo apt-get install -y --reinstall ttf-mscorefonts-installer
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh

script: "./travis/build.sh"

after_success:
- "./travis/publish.sh"

env:
  global:
  - GH_OAUTH_TOKEN: bcdcd15d4efcbf722592f348cf62cf7c07846574 # I'll leave this security hole for now 
  - GH_USER_NAME: xelav
  - GH_PROJECT_NAME: insider-threat-survey-2020
  - GIT_AUTHOR_NAME: xelav
  - GIT_AUTHOR_EMAIL: xelav.rus@gmail.com
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/survey.pdf
  - TZ="Europe/Moscow"
